### ISSUE TITLE
SVF RQ param range wrapping

### ISSUE THREAD

**Issue by catfact** [monome/aleph#145]
attempting weird 2.30 representation, with conditional shifts, to get 0-2 range from fract32 and a fixed-point param scaler. 

it's not working; the nominal range [0-1] is equivalent to [1,2].

**Comment by electropourlaction** [comment]
Trying to implement an interpolation algorithm that is using a 5/2 * FR32max constant, getting overflow errors, is there a way to work around this? a related question is how to handle mult calculations with values between 1 and 2, trying to split things up and adding the parts, that seems to work but at the cost of having to do more calculations.

**Comment by catfact** [comment]
in general the answer is to make a new set of arithmetic inlines for, say, 8.24 numbers. could be made fast with clever use of existing intrinsics (http://blackfin.uclinux.org/doku.php?id=toolchain:built-in_functions).

24.8 would be useful too (for sample interpolation)

**Comment by ghost** [comment]
calling this fixed!  We have another ticket for continuing work on svf (and maybe other) filter topologies
