### ISSUE TITLE
SVF saturation / damping

### ISSUE THREAD

**Issue by catfact** [monome/aleph#147]
SVF badly needs some form of soft clipping and/or RQ-dependent damping.

with strong harmonic input it clips very easily indeed! aleph-waves is currently using tiny little oscillator signals to compensate; kind of bad news.

made a start by testing some waveshaping algorithms, including a good softclipper. 

supercollider code in aleph/dsp/shapers.scd

**Comment by electropourlaction** [comment]
Is there a simple way, built-in or otherwise, to detect when a saturation/overflow occur? possible use would be a clipping indicator or to trig some kind of event.

**Comment by electropourlaction** [comment]
made some tests trying to add some interpolation on the svf filter, it sounds pretty nice but it clips very easily, especially with feedback or an aux return, and when it clips the sounds drops out (until user intervention), sometimes a drop out can happen pretty random too, not sure what that it though. anyway, here it is;

//a: cutoff, b: q-peak
fract32 env_bpf(env_tcd *env, fract32 a, fract32 b) {
    u8 i;

```
env->c0 = add_fr1x32(env->c0, mult_fr1x32x32(add_fr1x32(env->a, a), env->c2));
env->c1 = sub_fr1x32(sub_fr1x32(env->input(env), mult_fr1x32x32(sub_fr1x32(env->b, b), env->c2)), env->c0);
fract32 bp = add_fr1x32(env->c2, mult_fr1x32x32(add_fr1x32(env->a, a), env->c1));

fract32 y[4];
for (i=0; i<4; i++)
{
    static const u8 j[4] = { -1, 1 ,2 ,4 };
    y[i] = bp^j[i];
}
fract32 c0 = y[1];
fract32 c1 = sub_fr1x32(sub_fr1x32(y[2], mult_fr1x32x32(FR32_MAX1_3, y[0])), sub_fr1x32(mult_fr1x32x32(FR32_MAX1_2, y[1]), mult_fr1x32x32(FR32_MAX1_6, y[2])));
fract32 c2 = mult_fr1x32x32(FR32_MAX1_2, (sub_fr1x32(add_fr1x32(y[0], y[2]), y[1])));
fract32 c3 = add_fr1x32(mult_fr1x32x32(FR32_MAX1_6, sub_fr1x32(y[3], y[0])), mult_fr1x32x32(FR32_MAX1_2, sub_fr1x32(y[1], y[2])));
bp = add_fr1x32(c0, mult_fr1x32x32(bp, add_fr1x32(c1, mult_fr1x32x32(bp, add_fr1x32(c2, mult_fr1x32x32(bp, c3))))));

env->c2 = bp;

return bp;
```

}

coming back to my question above as I'm continuing to look for remedies to this problem, in the meantime I will do some more tests and see if there are any errors in the algorithm could be causing this as well!

**Comment by ghost** [comment]
Let's shovel some filter testbench into my analyser module to get this cooking.  Shouldn't be more than an evening or two's worth of work in linux/jack test environment.  I'm interested to understand & compare the benefits of oversampling here for the svf so will add the following to analyser (maybe rename it to DSP_testbench):
- 48kHz svf
- 2x up-sampled interpolated svf
- 48kHz svf w/ soft-clipping
- 2x up-sampled interpolated svf w/ soft-clipping

https://github.com/rick-monster/aleph/tree/dev/modules/analyser

some other useful/interesting blocks I might also chuck in there, mainly to have examples on hand when throwing together module ideas quickly:
- soft clipping (necessary prerequisite for clipping svf)
- improved zero-crossing pitch detection with better bandpass filter
- simple rotating-head pitchshift (grains' "scrubtap" pitchshift is all mangled up in the buffer logic)
- simple 16-bit & 32-bit cubic-interpolated delay lines
- dynamic range compression (think I can hack it together pretty quickly)
- adsr autowah/envelope shaping ( curious about the possiblities )
- a bitcrusher (easy, curious to experiment with the effect)

Feel like we're rapidly approach the point where the DSP directory has a 'complete' toolkit!  Any remaining gaping holes in the sample-by-sample processing library, when it comes to effect-processor primitives?

**Comment by ghost** [comment]
So I devised a soft-clipper algorithm, by fitting coefficients to a quadratic above some linear threshold:
https://github.com/rick-monster/aleph/blob/dev/dsp/ricks_tricks.c#L354-L438
Prototype here:
https://github.com/rick-monster/aleph/blob/dev/modules/analyser/soft_clip.c
Uses 1 or 2 divides, depending if you need the 'normalised' version or not, but all coefficients are all generated on the fly - no lookup tables or pre-calculated shapes required.

kind of interested to play around with one or more of these distortion elements in the feedback loop of karplus-strong.  Not quite sure how/where the clipping can be applied in svf filter - need to get a new filter testbench up and running, start playing around a bit...

**Comment by electropourlaction** [comment]
about missing effect-processor primitives, a dc removal algorithm would be awesome, if it can be done sample-by-sample.

**Comment by ghost** [comment]
Simplest DC removal can be highpass filter set to low freq.  Like this:

https://github.com/rick-monster/aleph/blob/dev/modules/grains/grains.c#L180
https://github.com/rick-monster/aleph/blob/dev/modules/grains/grains.c#L384-L385

If it's not possible to tune that down to low enough frequency (maybe I used 50Hz there because that's min. possible frequency for 1-pole LPF & bfin fractional mult), check the scaling technique here - used to achieve very slow slews (slew == low-pass filter):

https://github.com/rick-monster/aleph/blob/dev/dsp/ricks_tricks.c#L309-L317

The 1-pole high-pass filter is just the input signal minus it's low-pass filtered version I think.

**Comment by electropourlaction** [comment]
what would be the difference between an hpf and this?

https://ccrma.stanford.edu/~jos/fp/DC_Blocker.html

please help me understand.

**Comment by ghost** [comment]
oop - I dunno never seen that 'dc-blocker' algorithm.  You've plumbed the depths of my DSP knowledge.  That equation is _very_ easy to implement using the aleph fract primitives - I'll do some comparison in linux emulator when I get a minute...

**Comment by electropourlaction** [comment]
I got stuck trying to figure out if it requires block processing or not, would be very interested to hear your results.

**Comment by catfact** [comment]
@electropourlaction 
the one-pole, one-zero highpass that you link to is AFAICT exactly equivalent to subtracting the 1-pole lowpass of the signal, from the signal, as rick suggests.

miller puckette makes it more explicit
http://msp.ucsd.edu/techniques/v0.11/book-html/node141.html

you could use a 2nd order filter for steeper cutoff.

**Comment by ghost** [comment]
actually I would say the DC blocker algorithm there is ever-so subtly different to subtracting 1-pole lowpass (if you like being mindlessly pedantic, which I kind of do).  Here's the difference eqn for the 1-pole lpf:

lpf(n) = x(n) \* (1-R) + lpf(n-1) \* R

so the hpf:

hpf(n) = x(n) - lpf(n)
           = x(n) \* R - lpf(n-1) \* R
and:
lpf(n-1) = x(n-1) - hpf(n-1)
so:
hpf(n) = x(n) \* R - x(n-1) \* R + hpf(n-1) \* R
           = R \* ( x(n) + hpf(n-1) - x(n-1))

whereas dc_blocker(n) = x(n) - x(n-1) + R \* dc_blocker(n-1).  Just tested both ways, both use an add, a subtract and a mult, and seem _somewhat_ interchangeable...
https://github.com/rick-monster/aleph/commit/b1941ce33a696a1ebcc076b0f090afb36494def7

**Comment by catfact** [comment]
i guess the difference is the "normalization factor" that puckette describes. same as changing gain of lowpass before subtracting it, right?

**Comment by ghost** [comment]
Puckette kind of spun me out a bit to be honest with all that z-transform, unit circle jibber-jabber.  Should really sit and try and work through laplace transforms at some point...

But _can_ see that maybe those two difference equations are probably the same form with a linear coordinate transform.

**Comment by ghost** [comment]
So this 'easy' DC blocker question turned into yet another a lesson in pitfalls of fract DSP (and of emulation in general).  I actually experimented trying blasting 0dBFS white noise at the DC blocker, was seeing some unexpected results.  Eventually realised three very interesting things:
- there was a mistake how I cast floats to integer in bfin emulator main.c
- with full-scale white noise, even that 'simple' DC blocker algorithm requires a few bits headroom to not explode:
- one of those DC blocker algorithms has much less aliasing artefacts than the other! (though they both look pretty similar if you hit with white noise or a tone like 1k that fits an integer number of times into the sampling frequency)

https://github.com/rick-monster/aleph/commit/9726c50cd60936c49b9a5f3142843efd239c1b3b
http://rickvenn.com/dcblock1.png  for the function dc_block (dc_blocker from ccrma)
http://rickvenn.com/dcblock2.png for the function dc_block2 (canonical hpf)
http://rickvenn.com/dcblock_whitenoise.png spectrum looks the same for either flavour of the algorithm

**Comment by ghost** [comment]
meanwhile... back on topic here actually _is_ a first go at softclipping/damped version of the svf filter:
https://github.com/rick-monster/aleph/commit/11d3e5a18c9b1f524c3f1b785884814d44e8a578

According to emulator sims, this algorithm keeps the filter from hard clipping, using:
filter_svf_set_rq(&my_svf, FR32_MAX / 10);
(which should be q=5, right?) 
and tuning a full-scale sine wave right onto the resonance.  Also does some kind of interesting stuff when you add sine + noise, then drive into soft-clipping.  And with small signals, this soft-clipping algorithm adds no distortion.

So let's test on device, see if the promising simulation actually works in practice, also whether my naiive soft-clipping algorithm has an ok sound to it (and whether it makes a good secret sauce with the svf)...

**Comment by electropourlaction** [comment]
made some tests again with the library filter algorithms, sounds somewhat better now but I just feel there is something missing, it doesn't grab hold of the sound the way I want.

current state of things:
https://github.com/electropourlaction/aleph/blob/dev/modules/prgm/prgm.c#L1424

**Comment by ghost** [comment]
the soft-clipper could be improved, also maybe there's a better tweaking of the existing softclip algorithm for your taste.  Would be pretty easy to make softclip params part of some kind of svf object, to experiment a bit with the sound from BEES or prgrm.

but prioritising some work directly on BEES for now...

**Comment by electropourlaction** [comment]
thanks. but I have a strong hunch/feeling this is not about soft-clipping, but more about peculiarities with these algorithms.

for instance, one thing I have noticed is how the resonance is behaving, it is possible to ping it so some extent but normally a filter would build up to a position where it tips over and goes into self-oscillation, instead of doing so in the kind of a linear way this filter algorithm does.

another peculiar behaviour (maybe your scaling algorithms can come in handy here) is that the cutoff control would make more sense if it's range could be to limited from 0 to 12k or even 6k (this would be for a bandpass filter), while hopefully retaining full resolution, at least 0-FR32MAX.

anyway, best of luck with the work on BEES, I will go back to the drawing table again!

**Comment by catfact** [comment]
@electropourlaction 
apologies, i'm a bit confused. pulling your dev branch and looking at `prgrm`, the module doesn't seem to be using any SVF code from the library. the code you link (`pf_bpf()`) is some kind of 2nd-order structure that i don't recognize and can't easily parse... 

in fact your dev branch doesn't seem to have pulled in any of the upstream changes. are you commenting on the current sound of `lines` built from `monome/dev`? 

> build up to a position where it tips over and goes into self-oscillation, instead of doing so in the kind of a linear way this filter algorithm does.

so... you think RQ parameter should be mapped differently, maybe nonlinear? i wouldn't disagree, but i don't actually think that's the job of the DSP; it can be done on the control side (in the case of BEES, using an exponential param scaler.)

> range could be to limited from0 to 12k or even 6k (this would be for a bandpass filter)

but, the SVF of course isn't just a bandpass filter. having lowpass mode limited to 6k is... limiting. 
anyway, that is also a job for the control side. `filter_svf` will happily accept whatever coefficients you give it, and IMO it's better to pre-calculate them. i chose to use the same hz range as the oscillator parameters, just for convenience and to save storage (the table is calculated [here](https://github.com/catfact/aleph/blob/master/utils/param_scaling/scale_note_12tet.scd#L100) )

personally, i'm pretty happy with the soft clipper in the SVF loop. agree that it has plenty of areas for tweaking (especially w/r/t asymmetry.) as is, it lets us drive the filter with bigger signals without hard-clipping or adding much coloration. that was the point of this issue, so i think i'm going to close it for now - the conversation has wandered a bit in any case (though do feel free to keep it going of course.)

if _more_ coloration is desired, there's a lot of other ways to do that. it becomes quite a matter of taste. could mean adding more asymmetry. i've implemented a lot of these "valve emulation" kind of things, but never in such a constrained environment because you usually want 8x oversampling or something. tim goetze's [CAP plugins](quitte.de/dsp/caps.html) are a nice collection of static nonlinearity effects with source code, if you want to explore that.

**Comment by catfact** [comment]
in

**Comment by catfact** [comment]
by the way (OT, kinda) but would you have any interest in opening a pull request to add `prgrm` (module and avr32) to the upstream repo? no pressure of course, but people do enjoy using it.

**Comment by electropourlaction** [comment]
I agree that control side would limit the range of lets say cutoff, but the way I understand it is that this will also limit the resolution, is there a way have the filter take 0-6k while retaining 0-FR32MAX resolution?

> are you commenting on the current sound of lines built from monome/dev? 

no, I'm using the dsp library as a basis for a band pass filter, the link just show my latest attempt.

will look at at the soft-clipping algorithms again, it's just that I'm super scared of anything that spells clipping or distortion, as a general point of view! maybe we can call it something else :)

prgm has wandered a bit in it's own direction so I'm afraid that this could be causing a lot of trouble. some examples; I use 3 values in each parameter change command, the SPI command list is changed, the i2c driver is rewritten (maybe a good thing), added interrupts etc, but if it makes sense I do not mind adding it in, I'm just not sure if it's such a good idea!

lastly, I was a bit surprised that there was a note/popup about a pull request/change on the main aleph branch after I updated some files to my dev branch, I've gotten lazy nowadays and started to change stuff directly in the browser ui, but I can totally stop doing that if it affects the main branch!

**Comment by catfact** [comment]
> is there a way have the filter take 0-6k while retaining 0-FR32MAX resolution?

i really don't think that's an issue.
if you mean that you want a coefficient value of 0x7fffffff to equal a corner frequency of 6k in the SVF, then i think not, it would mean changing the sampling rate (to 12k.) at 48k and 2x oversampling, 6k gives a coefficient of 0x31F17078. 30 bits to represent all the lower frequencies should be plenty.

> prgm has wandered a bit in it's own direction

oh i see... looking more closely now. i didn't realize that you have made breaking changes to `avr32_lib` and `bfin_lib`; that does complicate things. 

but it also highlights the reasoning for keeping lib code separate from app code, and for keeping forks in sync. your i2c additions are close to what brian has added to ii drivers for the eurorack ecosystem in `libavr32` (which will soon be replacing `avr32_lib` in the upstream aleph repo.) and your additions to SPI protocol are parallel to additions i've been working on for filling wavetables from the avr32... 

and going in the other direction, i don't know, maybe you would like to use some of the new features that we get from `libavr32`, without having to re-develop them by hand: expanded MIDI, MSC driver, teletype protocol, maybe a better FAT system... 

but, if you want to keep your fork going totally independently, of course it's completely your call!

**Comment by electropourlaction** [comment]
if a merge would be done, would I need to make a big cleanup of my forked branch before making a  'prgm'-pull request? Or is the cleanup part of the pull request, e.g. would it be OK to make changes to the main branch for prgm to work with it too? like I really need my i2c-changes for my turntable sequencer to work.. I can write down a list of the main changes if that would be helpful for decision making.

**Comment by catfact** [comment]
let's be clear - by "main branch" i think you mean the upstream repository `monome/aleph`? we're talking about merging your `dev` branch into monome's `dev` branch. and no, you would never push changes to any branch on `monome/aleph`, just clean up your fork so that it would merge cleanly, and wouldn't break anything else; the easiest way to do that is to not change any library code, but non-breaking changes are probably fine. once it's clean you open a pull request so we can review and test it before actually changing the upstream repo.

if it were me, and i had (say) an i2c driver that really had to be totally different from monome's version (and couldn't be factored into an extra set of functions complementing the core), then i would just make a customized copy in my app folder, and not use the library version in my app project (the header might need to get a new name so that gcc doesn't include the wrong one.) same applies to sources in bfin_lib.

and again, maybe none of this is a priority for you, which is also completely fine and understandable! refactoring is not very fun, maybe it's not the way you want to spend your limited development time.

**Comment by electropourlaction** [comment]
ok, I think I get it and it sure would be a lot of work. at this point, I think I will start by keeping this in mind when I work on the app/module in my on dev branch, and hopefully along the way I can get to a point where it would be possible to add it to monome dev sometime later on.

**Comment by electropourlaction** [comment]
first of all I just want to say many thanks for the advice on the filter control, things got a whole lot better with non-linear control of cutoff and resonance indeed!

listening to what it sounds like after these improvements, I'm wondering if there is a possibility to add some kind of pre-emphasis/attenuation (not sure about the right word here) to balance the area around 150-350 Hz, it get's bumpy real easy, especially with a bit of resonance here. I guess how big this effect get's is of course much due to what is sent in, but compared to analogue filters and some listening test with different samples I still conclude that it would really help if it was possible to make some kind of balancing (without causing other problems like phase or loss of bottom end), could any of the algorithms in the dsp lib be used for this kind of task?!

**Comment by catfact** [comment]
just to make sure, you are talking about `filter_svf` from `aleph/dsp` right?

i think i might know what you mean by "bumpiness"... though my diagnosis is a little different. i don't think there's anything wrong with the frequency response. i've been running some tests with the scope, exciting the filter with continous white noise and different kinds of "ping." 

here's the [supercollider patch](https://gist.github.com/catfact/1b7b7fa9f4c82602b03b9ed405aff7ef) generating the excitation signals. there are 5 varieties:
- continuous white noise
- white noise with 1ms exponential decay envelope
- white noise with 0.01-0.1ms pulse rectangular envelope
- DC with 1ms exponential decay envelope
- DC with 0.01-0.1ms pulse rectangular envelope

if the rq is set to 0 and the filter is pinged with an envelope, sending it into oscillation, and the corner frequency subsequently swept, the frequency response is actually quite flat. the sine wave becomes distorted as CF approaches nyquist/2, as expected for this topology.

for RQ slightly >0, repeatedly sending a "decay DC" excitation has a predictable, smooth "ping". but repeatedly sending any of the others creates inconsistent amplitudes in the resulting sound. it is as if the system is not really LTI... feedback terms cancelling out new input. or something. i had noticed this before but attributed it to saturation during one or both of the summation steps.

however, softclipping isn't helping this particular issue (though it does i think improve the sound for typical uses cases when the input signal is hot.)

so i think you're right that it might be something totally wrong with the topology, event though it gives plausible results with most input. probably with the fixed-point implementation in particular.
i'm going to try redoing it. i've come across a couple of improved methods since 2012 or whatever anyway.

**Comment by electropourlaction** [comment]
> just to make sure, you are talking about filter_svf from aleph/dsp right?

yes.

this was an interesting read, will try and find the time to also try your pd-sounds with the current version, as a learning session for me.
